### ISSUE TITLE
Error on Video Encoding

### ISSUE THREAD

**Issue by mylespalmer** [thmsbfft/oryoki#13]
I've just been doing a screen recording (< 1minute in length) and had this error when stopping the recording.

To clear this error I had to go to the folder that it says, and then delete all of the contents and force quit the application & reboot.

I'm on 10.10.3 btw & attached is a screenshot.

![screen shot 2016-07-01 at 13 03 50](https://cloud.githubusercontent.com/assets/12728291/16522465/d9969952-3f95-11e6-8611-68cd79ddf4a7.png)

**Comment by thmsbfft** [comment]
Hmm. That'd be related to using 10.10.x. Video recording has to save every frame to a temporary folder, so that can be pretty intensive on older machines too.

I've been looking at ways of encoding frames directly into the video file but that doesn't seem to be possible as of now. Try using quicktime to record or update to 10.11.

**Comment by mylespalmer** [comment]
An odd one, having used it for a few more days (on the same setting) I am yet to experience anything similar.

Will report back if it raises it head!
