### ISSUE TITLE
Red dot during video recording

### ISSUE THREAD

**Issue by ayamflow** [thmsbfft/oryoki#14]
When you record a video, a blinking red dot shows up to remind you that it's recording 👍
However, it appears on the video itself.

Is this intentional, or is there a way for it to not be recorded with the website?

**Comment by thmsbfft** [comment]
I'm using it as otherwise it'd be easy to forget you're recording. It can be disabled in the preferences though, look for "display_recording_hint". Not ideal, thinking of another solution. Maybe a badge on the app icon?

I could probably also hide it before recording a frame / show after the frame has been recorded but that would make the fps super low, which is meh to record interactive stuff :/

**Comment by ayamflow** [comment]
I guess disabling it is good enough :) Badge would be cool tho
