### ISSUE TITLE
Vim keybindings?

### ISSUE THREAD

**Issue by hacktivateit** [thmsbfft/oryoki#4]
Something like cVim https://github.com/1995eaton/chromium-vim

**Comment by thmsbfft** [comment]
I'd love to do that but that seems like a big endeavor (lots of keys). Will look into it though. Being able to add chrome extensions to Oryoki/Electron would be a fantastic solve but it's not possible as of now: https://github.com/electron/electron/issues/1498

**Comment by danielmkarlsson** [comment]
+1 I also love me some Vim keybindings.
Totally understand about it seeming like a lot of keys and about how extensions can't work because reasons. 
but how about just the `j` key for scroll down and the `k` key for scroll up?
That's the one thing a Vimium fan really needs in order to browse the web without using the trackpad.
It would be so clean and smooth to have that.
